### PR TITLE
Replace a link to reddit with a local trimmed png

### PR DESCRIPTION
**Pull request by mexus**
There were some mumblings in `@rustjerk` about an external link (sic) so I've made a trimmed grayscale version of the logo and commited it as a binary file as an alternative of having an external link.

So I leave the decision to you whether or not to merge this change with a binary blob in it.

### CODE REVIEW

**Comment by qezz** [comment]
See #3 for more detailed results. 

Thank you for your time. Please use the proper emojis (👍or 👎) to express your feelings about this comment.

**Comment by kezvision** [comment]
See #3 for more detailed results.

Thank you for your time. Please use the proper emojis (👍or 👎) to express your feelings about this comment.

**Comment by mersinvald** [comment]
Btw, why is the picture grayscale?

**Comment by kezvision** [comment]
@mersinvald because we have no any favours to the colours. 
screen shot 2018-05-29 at 14 29 10

**Pull request merged**
